# Docker Compose file for the PDC's Hub Stack
#
#
# Used for collecting aggregate data queries.
#
# Use secondary .YML files for development and add -f YOUR.YML at execution.


composer:
  container_name: composer
  hostname: composer
  image: pdcbc/composer:${TAG}
  restart: always
  log_driver: "syslog"
  links:
    - hubdb:hubdb
  ports:
    - "2774:22"
    - "3002:3002"
  volumes:
    - /hdc/config/authorized_keys/:/home/autossh/.ssh/:rw
    - /hdc/config/composer_keys/:/etc/ssh/:rw
    - /hdc/config/scheduled_jobs/:/app/util/job_params/:rw


hubdb:
  container_name: hubdb
  hostname: hubdb
  image: pdcbc/hubdb:${TAG}
  restart: always
  log_driver: "syslog"
  volumes:
    - /hdc/private/mongo_live/:/data/db/:rw
    - /hdc/private/mongo_dump/:/data/dump/:rw
