# Docker Compose file for the HDC's Hub Stack
#
#
# Used for collecting aggregate data queries.
#
# Use secondary .YML files for development and add -f YOUR.YML at execution.


composer:
  container_name: composer
  hostname: composer
  image: healthdatacoalition/composer:${TAG}
  restart: always
  log_driver: "syslog"
  links:
    - composerdb:database
  ports:
    - "2774:22"
    - "3002:3002"
  volumes:
    - ${VOLS}/config/composer/:/config:rw


composerdb:
  container_name: composerdb
  hostname: composerdb
  image: mongo:3.2.9
  restart: always
  log_driver: "syslog"
  volumes:
    - ${VOLS}/private/composerDb/live/:/data/db/:rw
    - ${VOLS}/private/composerDb/dump/:/data/dump/:rw


endpoint:
  container_name: endpoint
  hostname: endpoint
  image: pdcbc/gateway:latest
  restart: always
  links:
    - composer:composer
  volumes:
    - ${VOLS}/private/endpoint:/volumes
  environment:
    - PORT_AUTOSSH=22
    - GATEWAY_ID=0
    - IP_COMPOSER=composer
