# Docker Compose file for the HDC's Hub Stack
#
#
# Used for collecting aggregate data queries.
#
# Use secondary .YML files for development and add -f YOUR.YML at execution.


composer:
  container_name: composer
  hostname: composer
  image: hdcbc/composer:${TAG}
  restart: always
  log_driver: "syslog"
  links:
    - composerdb
  ports:
    - "2774:22"
    - "3002:3002"
  volumes:
    - ${VOLS}/config/composer:/config:rw
    - ${VOLS}/private/composerDb/dump:/dump:rw


composerdb:
  container_name: composerdb
  hostname: composerdb
  image: mongo:3.2.9
  restart: always
  log_driver: "syslog"
  volumes:
    - ${VOLS}/private/composerDb/live/:/data/db/:rw


gateway:
  container_name: gateway
  hostname: gateway
  image: hdcbc/gateway:latest
  restart: always
  links:
    - composer
    - gatewaydb:database
  volumes:
    - ${VOLS}/config/gateway:/home/autossh/.ssh/
  environment:
    - PORT_AUTOSSH=22
    - GATEWAY_ID=0
    - IP_COMPOSER=composer


gatewaydb:
  container_name: gatewaydb
  hostname: gatewaydb:database
  image: mongo:3.2.9
  restart: always
