# Docker Compose file for the PDC's Hub Stack
#
#
# Used for collecting aggregate data queries.
#
# Use secondary .YML files for development and add -f YOUR.YML at execution.


cadvisor:
  container_name: cadvisor
  image: google/cadvisor:latest
  restart: always
  ports:
    - "8080:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro


#owncloud:
#  container_name: owncloud
#  hostname: owncloud
#  image: pdcbc/owncloud:${TAG}
#  restart: always
#  log_driver: "syslog"
#  volumes:
#    - /pdc/data/config/dacs/:/etc/dacs/:rw
#    - /pdc/data/config/authorized_keys/:/home/autossh/.ssh/:rw
#    - /pdc/data/config/composer_keys/:/etc/ssh/
#    - /pdc/data/config/scheduled_jobs/:/app/util/job_params:rw
#    - /pdc/data/config/groups/:/home/app/groups:rw
#    - /pdc/data/private/mongo_live/:/data/db/:rw
#    - /pdc/data/private/mongo_dump/:/data/dump/:rw
